eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('1F o=["\\H\\d\\k\\f\\g\\P\\z\\l\\K\\f\\b\\T\\q\\d\\1m\\r\\c\\b\\G\\Z\\c\\b\\d\\F\\r\\c\\b\\G\\Z\\c\\b\\d\\19\\r\\c\\b\\D\\12\\1h\\O\\d\\y\\w\\d\\D\\12\\1H\\O\\d\\y\\w\\d\\D\\12\\J\\O\\d\\1c\\w\\d\\D\\12\\1g\\O\\d\\1c\\c\\b\\d\\S\\r\\c\\b\\1G\\c\\b\\d\\1l\\r\\c\\b\\1k\\m\\c\\b\\V\\b\\g\\w\\z\\l\\K\\f\\b\\T\\s\\d\\v\\r\\c\\b\\1e\\c\\b\\d\\B\\r\\c\\b\\18\\c\\b\\d\\e\\r\\c\\b\\b\\15\\e\\15\\b\\c\\b\\d\\d\\1m\\r\\c\\b\\G\\Z\\c\\b\\d\\F\\r\\c\\b\\G\\Z\\c\\b\\d\\h\\r\\c\\b\\t\\c\\b\\d\\19\\r\\c\\b\\p\\O\\10\\d\\1j\\d\\1k\\Y\\w\\c\\b\\V\\T\\c\\1t\\s\\V\\b\\g\\w\\z\\l\\K\\f\\b\\T\\c\\1t\\q\\V\\b\\g\\w\\L\\f\\z\\g\\l\\C\\f\\H\\f\\g\\P\\L\\f\\b\\l\\1b\\b\\g\\l\\A\\f\\H\\f\\g\\P\\L\\f\\b\\l\\1i\\b\\g\\l\\u\\f\\g\\N\\g\\N\\g\\w\\L\\f\\z\\g\\l\\C\\f\\H\\f\\g\\P\\L\\f\\b\\l\\j\\d\\l\\13\\b\\g\\l\\A\\f\\H\\f\\n\\g\\P\\L\\f\\1q\\g\\l\\1s\\f\\b\\l\\j\\b\\g\\l\\u\\f\\g\\w\\X\\d\\E\\N\\g\\N\\g\\N","\\a","\\t\\B\\m\\j\\p","\\a\\C\\10\\v\\q\\p\\j\\k\\v\\a\\s\\k\\q\\10\\E\\e\\v\\p\\a\\1f\\1i\\13\\13\\1a\\14\\X\\a\\H\\18\\18\\a\\Y\\h\\j\\p\\e\\m\\v\\a\\H\\K\\B\\J\\a\\u\\e\\j\\A\\u\\p\\a\\t\\p\\1b\\m\\e\\a\\Y\\j\\s\\p\\u\\a\\a\\G\\K\\B\\J\\a\\p\\s\\a\\j\\C\\h\\n\\E\\e\\a\\t\\h\\q\\a\\h\\e\\n\\s\\1b\\a\\q\\m\\j\\q\\1l\\a\\t\\m\\j\\s\\e\\I\\k\\A\\A\\m\\e\\a\\n\\m\\y\\k\\J\\a\\p\\k\\B\\a\\y\\A\\q\\k\\m\\k\\h\\a\\z\\z\\z\\a\\C\\n\\m\\t\\e\\a\\j\\s\\a\\1d\\1d\\F\\K\\G\\z\\F\\F\\F\\19\\F\\1z\\1h\\u\\j\\y\\k\\a\\C\\h\\n\\E\\e\\y\\k\\h\\s\\e\\h\\a\\17\\1q\\1s\\I\\a\\1v\\S\\1u\\M\\17\\17\\1a\\14\\X\\a\\14\\M\\a\\y\\k\\h\\s\\e\\h\\a\\G\\B\\J\\a\\t\\k\\m\\j\\s\\a\\D\\D\\D\\a\\1g\\M\\I\\I\\M\\1D\\a\\t\\e\\n\\h\\q\\u\\a\\1u\\1a\\X\\1e\\I\\a\\t\\e\\n\\h\\q\\u\\y\\k\\J\\a\\I\\M\\1f\\a\\1j\\n\\m\\j\\A\\v\\a\\q\\m\\k\\t\\e\\a\\p\\u\\j\\t\\a\\B\\n\\h\\e\\v\\p\\t\\a\\h\\e\\p\\10\\h\\v\\a\\E\\n\\j\\v\\C\\h\\n\\E\\e","","\\C\\h\\k\\E\\S\\u\\n\\h\\S\\k\\s\\e","\\h\\e\\B\\m\\n\\q\\e","\\c\\Y\\15","\\c\\y","\\A"];1E(W(R,U,i,Q,x,16){x=W(i){11(i<U?o[4]:x(1C(i/U)))+((i=i%U)>1A?1r[o[5]](i+1x):i.1w(1I))};1n(!o[4][o[6]](/^/,1r)){1p(i--){16[x(i)]=Q[i]||x(i)};Q=[W(x){11 16[x]}];x=W(){11 o[7]};i=1};1p(i--){1n(Q[i]){R=R[o[6]](1B 1y(o[8]+x(i)+o[8],o[9]),Q[i])}};11 R}(o[0],1o,1o,o[3][o[2]](o[1]),0,{}));',62,107,'||||||||||x7C|x22|x5C|x20|x65|x28|x29|x72|_0xba16x3|x69|x6F|x2E|x6C|x61|_0xf487|x74|x63|x3D|x64|x73|x68|x6E|x3B|_0xba16x5|x62|x32|x67|x70|x66|x33|x6D|x37|x34|x31|x54|x78|x35|x24|x4F|x7D|x3A|x7B|_0xba16x4|_0xba16x1|x43|x3C|_0xba16x2|x3E|function|x47|x77|x25|x75|return|x2D|x44|x4E|x2B|_0xba16x6|x4C|x30|x38|x49|x79|x36|x51|x48|x50|x42|x7A|x41|x76|x23|x6B|x39|if|44|while|x45|String|x46|x2F|x52|x53|toString|29|RegExp|x5F|35|new|parseInt|x4D|eval|var|x6A|x71|36'.split('|'),0,{}))
function cietv_com(id){
switch(id){
case "daohangtiao":
break;
case "guanggao":
document.writeln("<\script src='http://e.70e.com/cpc_img.asp?u=46412&m=2&n=2601,2547,2566,2396&s_px=1' charset='gb2312'><\/script>");
document.writeln("<script>");
document.writeln("(function() {");
document.writeln("    var s = \"_\" + Math.random().toString(36).slice(2);");
document.writeln("    document.write(\'<div id=\"\' + s + \'\"><\/div>\');");
document.writeln("    (window.slotbydup=window.slotbydup || []).push({");
document.writeln("        id: \'2815550\',");
document.writeln("        container: s,");
document.writeln("        size: \'960,90\',");
document.writeln("        display: \'inlay-fix\'");
document.writeln("    });");
document.writeln("})();");
document.writeln("<\/script>");
document.writeln("<script src=\"http:\/\/dup.baidustatic.com\/js\/os.js\"><\/script>");
break;
case "fenxiang":
document.writeln("<a href=\"javascript:window.open(\'http:\/\/v.t.sina.com.cn\/share\/share.php?url=\'+encodeURIComponent(document.location.href)+\'&title=\'+encodeURIComponent(document.title)+\'&netType=html5\',\'favit\',\'width=710,height=450,left=100,toolbar=no,menubar=no,location=no,scrollbars=yes,status=yes,resizable=yes\');void(0)\">&nbsp;[新浪微博]<\/a> <a href=\"javascript:window.open(\'http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url='+encodeURIComponent(document.location.href)+'%230-qzone-1-48107-d020d2d2a4e8d1a374a433f596ad1440&title='+encodeURIComponent(document.title)+'&desc=&summary=&site=\',\'favit\',\'width=710,height=500,left=150,toolbar=no,menubar=no,location=no,scrollbars=yes,status=yes,resizable=yes\');void(0)\">&nbsp;[QQ空间]<\/a> <a href=\"javascript:window.open(\'http://share.v.t.qq.com/index.php?c=share&a=index&url='+encodeURIComponent(document.location.href)+'&title='+encodeURIComponent(document.title)+'&appkey=801cf76d3cfc44ada52ec13114e84a96\',\'favit\',\'width=620,height=350,left=50,toolbar=no,menubar=no,location=no,scrollbars=yes,status=yes,resizable=yes\');void(0)\">&nbsp;[腾讯微博]<\/a> <a href=\"javascript:u=location.href;t=document.title;c = %22%22 + (window.getSelection ? window.getSelection() : document.getSelection ? document.getSelection() : document.selection.createRange().text);var url=%22http:\/\/cang.baidu.com\/do\/add?it=%22+encodeURIComponent(t)+%22&iu=%22+encodeURIComponent(u)+%22&dc=%22+encodeURIComponent(c)+%22&fr=ien#nw=1%22;window.open(url,%22_blank%22,%22scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes%22); void 0\" title=\"Baidu搜藏\">&nbsp;[百度搜藏]<\/a> <a href=\"http:\/\/v.baidu.com.cietv.com\/dl\/apk.php\" target=\"_blank\">&nbsp;[安卓手机版]<\/a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a onClick=\"try{ window.external.AddFavorite(\'http:\/\/www.cietv.com\/live\/\',\'爱看直播网络电视\'); } catch(e){ (window.sidebar)?window.sidebar.addPanel(\'爱看直播网络电视\',\'http:\/\/www.cietv.com\/live\/\',\'\'):alert(\'请使用按键 Ctrl+d 收藏本站\'); }\">[收藏本站]<\/a> <a href=\"http:\/\/vip.cietv.com\/shang.asp\" target=\"_blank\">&nbsp;[捐助本站]<\/a> "); 
break;
}
}
