document.writeln("<div id=\"panel2\">");
document.writeln("<div class=\"skinnav\"> ");
document.writeln("<ul id=\"tags\">");
document.writeln("<div class=\"skinok\"><a href=\"#\" class=\"btn-slide\" title=\"保存皮肤\" onClick=\"fn(this,2)\"  target=\"_self\">收起</a></div>");
document.writeln("<div class=\"skinok2\"><a class=\"bg_a_8\" href=\"#\" id=\"bg_a_8\"  target=\"_self\">还原默认</a></div>");
document.writeln("<div class=\"skinok2\"><a class=\"bg0\" href=\"#\" id=\"bg0\"  target=\"_self\">不使用背景</a></div>");
document.writeln("<li><a href=\"#\" onClick=\"changeBody(1)\"  target=\"_self\">简约色调</a></li>");
document.writeln("<li><a href=\"#\" onClick=\"changeBody(2)\"  target=\"_self\">偶像明星</a></li>");
document.writeln("<li><a href=\"#\" onClick=\"changeBody(3)\"  target=\"_self\">风景静物</a></li>");
document.writeln("<li><a href=\"#\" onClick=\"changeBody(4)\"  target=\"_self\">手绘卡通</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div id=\"Js_pic1\" class=\"skinbox-wrapper\">");
document.writeln("<div class=\"skinbox\">");
document.writeln("<ul class=\"my_skin\">");
document.writeln("<li class=\"bg_a_1\"><a href=\"#\" id=\"bg_a_1\"><img src=\"/Skins/mb/img/skin/bg_a_1_s.jpg\"/><span>爸爸去哪</span></a></li>");
document.writeln("<li class=\"bg_a_2\"><a href=\"#\" id=\"bg_a_2\"><img src=\"/Skins/mb/img/skin/bg_a_2_s.jpg\"/><span>林荫小道</span></a></li>");
document.writeln("<li class=\"bg_a_3\"><a href=\"#\" id=\"bg_a_3\"><img src=\"/Skins/mb/img/skin/bg_a_3_s.jpg\"/><span>树荫下的女孩</span></a></li>");
document.writeln("<li class=\"bg_a_8\"><a href=\"#\" id=\"bg_a_8\"><img src=\"/Skins/mb/img/skin/bg_a_8_s.jpg\"/><span>Hello Kitty</span></a></li>");
document.writeln("<li class=\"bg_a_4\"><a href=\"#\" id=\"bg_a_4\"><img src=\"/Skins/mb/img/skin/bg_a_4_s.jpg\"/><span>热气球</span></a></li>");
document.writeln("<li class=\"bg_a_5\"><a href=\"#\" id=\"bg_a_5\"><img src=\"/Skins/mb/img/skin/bg_a_5_s.jpg\"/><span>清明时节</span></a></li>");
document.writeln("<li class=\"bg_a_6\"><a href=\"#\" id=\"bg_a_6\"><img src=\"/Skins/mb/img/skin/bg_a_6_s.jpg\"/><span>春之路</span></a></li>");
document.writeln("<li class=\"bg_a_7\"><a href=\"#\" id=\"bg_a_7\"><img src=\"/Skins/mb/img/skin/bg_a_7_s.jpg\"/><span>立夏</span></a></li>");
document.writeln("<li class=\"bg_a_9\"><a href=\"#\" id=\"bg_a_9\"><img src=\"/Skins/mb/img/skin/bg_a_9_s.jpg\"/><span>小署</span></a></li>");
document.writeln("<li class=\"bg_a_10\"><a href=\"#\" id=\"bg_a_10\"><img src=\"/Skins/mb/img/skin/bg_a_10_s.jpg\"/><span>童话世界</span></a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div id=\"Js_pic2\"  class=\"skinbox-wrapper\">");
document.writeln("<div class=\"skinbox\">");
document.writeln("<ul class=\"my_skin\">");
document.writeln("<li class=\"bg_b_1\"><a href=\"#\" id=\"bg_b_1\"><img src=\"/Skins/mb/img/skin/bg_b_1_s.jpg\"/><span>古天乐</span></a></li>");
document.writeln("<li class=\"bg_b_2\"><a href=\"#\" id=\"bg_b_2\"><img src=\"/Skins/mb/img/skin/bg_b_2_s.jpg\"/><span>刘烨</span></a></li>");
document.writeln("<li class=\"bg_b_3\"><a href=\"#\" id=\"bg_b_3\"><img src=\"/Skins/mb/img/skin/bg_b_3_s.jpg\"/><span>那英</span></a></li>");
document.writeln("<li class=\"bg_b_4\"><a href=\"#\" id=\"bg_b_4\"><img src=\"/Skins/mb/img/skin/bg_b_4_s.jpg\"/><span>吴尊</span></a></li>");
document.writeln("<li class=\"bg_b_5\"><a href=\"#\" id=\"bg_b_5\"><img src=\"/Skins/mb/img/skin/bg_b_5_s.jpg\"/><span>黄渤</span></a></li>");
document.writeln("<li class=\"bg_b_6\"><a href=\"#\" id=\"bg_b_6\"><img src=\"/Skins/mb/img/skin/bg_b_6_s.jpg\"/><span>内马尔</span></a></li>");
document.writeln("<li class=\"bg_b_7\"><a href=\"#\" id=\"bg_b_7\"><img src=\"/Skins/mb/img/skin/bg_b_7_s.jpg\"/><span>莱昂纳多</span></a></li>");
document.writeln("<li class=\"bg_b_8\"><a href=\"#\" id=\"bg_b_8\"><img src=\"/Skins/mb/img/skin/bg_b_8_s.jpg\"/><span>少女时代</span></a></li>");
document.writeln("<li class=\"bg_b_9\"><a href=\"#\" id=\"bg_b_9\"><img src=\"/Skins/mb/img/skin/bg_b_9_s.jpg\"/><span>步步惊情</span></a></li>");
document.writeln("<li class=\"bg_b_10\"><a href=\"#\" id=\"bg_b_10\"><img src=\"/Skins/mb/img/skin/bg_b_10_s.jpg\"/><span>EXO</span></a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div id=\"Js_pic3\"  class=\"skinbox-wrapper\">");
document.writeln("<div class=\"skinbox\">");
document.writeln("<ul class=\"my_skin\">");
document.writeln("<li class=\"bg_c_1\"><a href=\"#\" id=\"bg_c_1\"><img src=\"/Skins/mb/img/skin/bg_c_1_s.jpg\"/><span>粉色回忆</span></a></li>");
document.writeln("<li class=\"bg_c_2\"><a href=\"#\" id=\"bg_c_2\"><img src=\"/Skins/mb/img/skin/bg_c_2_s.jpg\"/><span>招财童子</span></a></li>");
document.writeln("<li class=\"bg_c_3\"><a href=\"#\" id=\"bg_c_3\"><img src=\"/Skins/mb/img/skin/bg_c_3_s.jpg\"/><span>绿意盎然</span></a></li>");
document.writeln("<li class=\"bg_c_4\"><a href=\"#\" id=\"bg_c_4\"><img src=\"/Skins/mb/img/skin/bg_c_4_s.jpg\"/><span>天空之城</span></a></li>");
document.writeln("<li class=\"bg_c_5\"><a href=\"#\" id=\"bg_c_5\"><img src=\"/Skins/mb/img/skin/bg_c_5_s.jpg\"/><span>清凉一夏</span></a></li>");
document.writeln("<li class=\"bg_c_6\"><a href=\"#\" id=\"bg_c_6\"><img src=\"/Skins/mb/img/skin/bg_c_6_s.jpg\"/><span>夏至</span></a></li>");
document.writeln("<li class=\"bg_c_7\"><a href=\"#\" id=\"bg_c_7\"><img src=\"/Skins/mb/img/skin/bg_c_7_s.jpg\"/><span>初夏</span></a></li>");
document.writeln("<li class=\"bg_c_8\"><a href=\"#\" id=\"bg_c_8\"><img src=\"/Skins/mb/img/skin/bg_c_8_s.jpg\"/><span>蚂蚁搬家</span></a></li>");
document.writeln("<li class=\"bg_c_9\"><a href=\"#\" id=\"bg_c_9\"><img src=\"/Skins/mb/img/skin/bg_c_9_s.jpg\"/><span>海滩</span></a></li>");
document.writeln("<li class=\"bg_c_10\"><a href=\"#\" id=\"bg_c_10\"><img src=\"/Skins/mb/img/skin/bg_c_10_s.jpg\"/><span>春天里的樱花</span></a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div id=\"Js_pic4\" class=\"skinbox-wrapper\">");
document.writeln("<div  class=\"skinbox\">");
document.writeln("<ul class=\"my_skin\">");
document.writeln("<li class=\"bg_d_1\"><a href=\"#\" id=\"bg_d_1\"><img src=\"/Skins/mb/img/skin/bg_d_1_s.jpg\"/><span>炮炮兵</span></a></li>");
document.writeln("<li class=\"bg_d_2\"><a href=\"#\" id=\"bg_d_2\"><img src=\"/Skins/mb/img/skin/bg_d_2_s.jpg\"/><span>进攻的武士</span></a></li>");
document.writeln("<li class=\"bg_d_3\"><a href=\"#\" id=\"bg_d_3\"><img src=\"/Skins/mb/img/skin/bg_d_3_s.jpg\"/><span>卡通猫情侣</span></a></li>");
document.writeln("<li class=\"bg_d_4\"><a href=\"#\" id=\"bg_d_4\"><img src=\"/Skins/mb/img/skin/bg_d_4_s.jpg\"/><span>羊羊大吉</span></a></li>");
document.writeln("<li class=\"bg_d_5\"><a href=\"#\" id=\"bg_d_5\"><img src=\"/Skins/mb/img/skin/bg_d_5_s.jpg\"/><span>新年红包</span></a></li>");
document.writeln("<li class=\"bg_d_6\"><a href=\"#\" id=\"bg_d_6\"><img src=\"/Skins/mb/img/skin/bg_d_6_s.jpg\"/><span>花旦名角</span></a></li>");
document.writeln("<li class=\"bg_d_7\"><a href=\"#\" id=\"bg_d_7\"><img src=\"/Skins/mb/img/skin/bg_d_7_s.jpg\"/><span>江南春晓</span></a></li>");
document.writeln("<li class=\"bg_d_8\"><a href=\"#\" id=\"bg_d_8\"><img src=\"/Skins/mb/img/skin/bg_d_8_s.jpg\"/><span>历史怀旧</span></a></li>");
document.writeln("<li class=\"bg_d_9\"><a href=\"#\" id=\"bg_d_9\"><img src=\"/Skins/mb/img/skin/bg_d_9_s.jpg\"/><span>追忆时光</span></a></li>");
document.writeln("<li class=\"bg_d_10\"><a href=\"#\" id=\"bg_d_10\"><img src=\"/Skins/mb/img/skin/bg_d_10_s.jpg\"/><span>单车岁月</span></a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("</div>");